#ifndef CONFIG_H
#define CONFIG_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define CELL_SIZE 4
#define GRID_WIDTH SCREEN_WIDTH/CELL_SIZE
#define GRID_HEIGHT SCREEN_HEIGHT/CELL_SIZE
#define UPDATE_RATE 0.02f

#endif